/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorontoRouteImport } from './routes/toronto'
import { Route as SaasRouteImport } from './routes/saas'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotALeadsProblemRouteImport } from './routes/not-a-leads-problem'
import { Route as MetaAdsRouteImport } from './routes/meta-ads'
import { Route as LocalServicesRouteImport } from './routes/local-services'
import { Route as HvacRouteImport } from './routes/hvac'
import { Route as GtaSmallBusinessRouteImport } from './routes/gta-small-business'
import { Route as GrowthCeilingRouteImport } from './routes/growth-ceiling'
import { Route as GrowthCalculatorRouteImport } from './routes/growth-calculator'
import { Route as FreeAuditRouteImport } from './routes/free-audit'
import { Route as EcommerceRouteImport } from './routes/ecommerce'
import { Route as ConsumerFinanceRouteImport } from './routes/consumer-finance'
import { Route as CacCalculatorRouteImport } from './routes/cac-calculator'
import { Route as BookRouteImport } from './routes/book'
import { Route as ApplianceRepairRouteImport } from './routes/appliance-repair'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesSocietyMortgageRouteImport } from './routes/case-studies.society-mortgage'
import { Route as CaseStudiesMountainGamingRouteImport } from './routes/case-studies.mountain-gaming'

const TorontoRoute = TorontoRouteImport.update({
  id: '/toronto',
  path: '/toronto',
  getParentRoute: () => rootRouteImport,
} as any)
const SaasRoute = SaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotALeadsProblemRoute = NotALeadsProblemRouteImport.update({
  id: '/not-a-leads-problem',
  path: '/not-a-leads-problem',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaAdsRoute = MetaAdsRouteImport.update({
  id: '/meta-ads',
  path: '/meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalServicesRoute = LocalServicesRouteImport.update({
  id: '/local-services',
  path: '/local-services',
  getParentRoute: () => rootRouteImport,
} as any)
const HvacRoute = HvacRouteImport.update({
  id: '/hvac',
  path: '/hvac',
  getParentRoute: () => rootRouteImport,
} as any)
const GtaSmallBusinessRoute = GtaSmallBusinessRouteImport.update({
  id: '/gta-small-business',
  path: '/gta-small-business',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthCeilingRoute = GrowthCeilingRouteImport.update({
  id: '/growth-ceiling',
  path: '/growth-ceiling',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthCalculatorRoute = GrowthCalculatorRouteImport.update({
  id: '/growth-calculator',
  path: '/growth-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeAuditRoute = FreeAuditRouteImport.update({
  id: '/free-audit',
  path: '/free-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceRoute = EcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerFinanceRoute = ConsumerFinanceRouteImport.update({
  id: '/consumer-finance',
  path: '/consumer-finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CacCalculatorRoute = CacCalculatorRouteImport.update({
  id: '/cac-calculator',
  path: '/cac-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplianceRepairRoute = ApplianceRepairRouteImport.update({
  id: '/appliance-repair',
  path: '/appliance-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSocietyMortgageRoute =
  CaseStudiesSocietyMortgageRouteImport.update({
    id: '/case-studies/society-mortgage',
    path: '/case-studies/society-mortgage',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudiesMountainGamingRoute =
  CaseStudiesMountainGamingRouteImport.update({
    id: '/case-studies/mountain-gaming',
    path: '/case-studies/mountain-gaming',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appliance-repair': typeof ApplianceRepairRoute
  '/book': typeof BookRoute
  '/cac-calculator': typeof CacCalculatorRoute
  '/consumer-finance': typeof ConsumerFinanceRoute
  '/ecommerce': typeof EcommerceRoute
  '/free-audit': typeof FreeAuditRoute
  '/growth-calculator': typeof GrowthCalculatorRoute
  '/growth-ceiling': typeof GrowthCeilingRoute
  '/gta-small-business': typeof GtaSmallBusinessRoute
  '/hvac': typeof HvacRoute
  '/local-services': typeof LocalServicesRoute
  '/meta-ads': typeof MetaAdsRoute
  '/not-a-leads-problem': typeof NotALeadsProblemRoute
  '/privacy': typeof PrivacyRoute
  '/saas': typeof SaasRoute
  '/toronto': typeof TorontoRoute
  '/case-studies/mountain-gaming': typeof CaseStudiesMountainGamingRoute
  '/case-studies/society-mortgage': typeof CaseStudiesSocietyMortgageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appliance-repair': typeof ApplianceRepairRoute
  '/book': typeof BookRoute
  '/cac-calculator': typeof CacCalculatorRoute
  '/consumer-finance': typeof ConsumerFinanceRoute
  '/ecommerce': typeof EcommerceRoute
  '/free-audit': typeof FreeAuditRoute
  '/growth-calculator': typeof GrowthCalculatorRoute
  '/growth-ceiling': typeof GrowthCeilingRoute
  '/gta-small-business': typeof GtaSmallBusinessRoute
  '/hvac': typeof HvacRoute
  '/local-services': typeof LocalServicesRoute
  '/meta-ads': typeof MetaAdsRoute
  '/not-a-leads-problem': typeof NotALeadsProblemRoute
  '/privacy': typeof PrivacyRoute
  '/saas': typeof SaasRoute
  '/toronto': typeof TorontoRoute
  '/case-studies/mountain-gaming': typeof CaseStudiesMountainGamingRoute
  '/case-studies/society-mortgage': typeof CaseStudiesSocietyMortgageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appliance-repair': typeof ApplianceRepairRoute
  '/book': typeof BookRoute
  '/cac-calculator': typeof CacCalculatorRoute
  '/consumer-finance': typeof ConsumerFinanceRoute
  '/ecommerce': typeof EcommerceRoute
  '/free-audit': typeof FreeAuditRoute
  '/growth-calculator': typeof GrowthCalculatorRoute
  '/growth-ceiling': typeof GrowthCeilingRoute
  '/gta-small-business': typeof GtaSmallBusinessRoute
  '/hvac': typeof HvacRoute
  '/local-services': typeof LocalServicesRoute
  '/meta-ads': typeof MetaAdsRoute
  '/not-a-leads-problem': typeof NotALeadsProblemRoute
  '/privacy': typeof PrivacyRoute
  '/saas': typeof SaasRoute
  '/toronto': typeof TorontoRoute
  '/case-studies/mountain-gaming': typeof CaseStudiesMountainGamingRoute
  '/case-studies/society-mortgage': typeof CaseStudiesSocietyMortgageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appliance-repair'
    | '/book'
    | '/cac-calculator'
    | '/consumer-finance'
    | '/ecommerce'
    | '/free-audit'
    | '/growth-calculator'
    | '/growth-ceiling'
    | '/gta-small-business'
    | '/hvac'
    | '/local-services'
    | '/meta-ads'
    | '/not-a-leads-problem'
    | '/privacy'
    | '/saas'
    | '/toronto'
    | '/case-studies/mountain-gaming'
    | '/case-studies/society-mortgage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appliance-repair'
    | '/book'
    | '/cac-calculator'
    | '/consumer-finance'
    | '/ecommerce'
    | '/free-audit'
    | '/growth-calculator'
    | '/growth-ceiling'
    | '/gta-small-business'
    | '/hvac'
    | '/local-services'
    | '/meta-ads'
    | '/not-a-leads-problem'
    | '/privacy'
    | '/saas'
    | '/toronto'
    | '/case-studies/mountain-gaming'
    | '/case-studies/society-mortgage'
  id:
    | '__root__'
    | '/'
    | '/appliance-repair'
    | '/book'
    | '/cac-calculator'
    | '/consumer-finance'
    | '/ecommerce'
    | '/free-audit'
    | '/growth-calculator'
    | '/growth-ceiling'
    | '/gta-small-business'
    | '/hvac'
    | '/local-services'
    | '/meta-ads'
    | '/not-a-leads-problem'
    | '/privacy'
    | '/saas'
    | '/toronto'
    | '/case-studies/mountain-gaming'
    | '/case-studies/society-mortgage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplianceRepairRoute: typeof ApplianceRepairRoute
  BookRoute: typeof BookRoute
  CacCalculatorRoute: typeof CacCalculatorRoute
  ConsumerFinanceRoute: typeof ConsumerFinanceRoute
  EcommerceRoute: typeof EcommerceRoute
  FreeAuditRoute: typeof FreeAuditRoute
  GrowthCalculatorRoute: typeof GrowthCalculatorRoute
  GrowthCeilingRoute: typeof GrowthCeilingRoute
  GtaSmallBusinessRoute: typeof GtaSmallBusinessRoute
  HvacRoute: typeof HvacRoute
  LocalServicesRoute: typeof LocalServicesRoute
  MetaAdsRoute: typeof MetaAdsRoute
  NotALeadsProblemRoute: typeof NotALeadsProblemRoute
  PrivacyRoute: typeof PrivacyRoute
  SaasRoute: typeof SaasRoute
  TorontoRoute: typeof TorontoRoute
  CaseStudiesMountainGamingRoute: typeof CaseStudiesMountainGamingRoute
  CaseStudiesSocietyMortgageRoute: typeof CaseStudiesSocietyMortgageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toronto': {
      id: '/toronto'
      path: '/toronto'
      fullPath: '/toronto'
      preLoaderRoute: typeof TorontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saas': {
      id: '/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof SaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-a-leads-problem': {
      id: '/not-a-leads-problem'
      path: '/not-a-leads-problem'
      fullPath: '/not-a-leads-problem'
      preLoaderRoute: typeof NotALeadsProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-ads': {
      id: '/meta-ads'
      path: '/meta-ads'
      fullPath: '/meta-ads'
      preLoaderRoute: typeof MetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-services': {
      id: '/local-services'
      path: '/local-services'
      fullPath: '/local-services'
      preLoaderRoute: typeof LocalServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hvac': {
      id: '/hvac'
      path: '/hvac'
      fullPath: '/hvac'
      preLoaderRoute: typeof HvacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gta-small-business': {
      id: '/gta-small-business'
      path: '/gta-small-business'
      fullPath: '/gta-small-business'
      preLoaderRoute: typeof GtaSmallBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-ceiling': {
      id: '/growth-ceiling'
      path: '/growth-ceiling'
      fullPath: '/growth-ceiling'
      preLoaderRoute: typeof GrowthCeilingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-calculator': {
      id: '/growth-calculator'
      path: '/growth-calculator'
      fullPath: '/growth-calculator'
      preLoaderRoute: typeof GrowthCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-audit': {
      id: '/free-audit'
      path: '/free-audit'
      fullPath: '/free-audit'
      preLoaderRoute: typeof FreeAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce': {
      id: '/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof EcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer-finance': {
      id: '/consumer-finance'
      path: '/consumer-finance'
      fullPath: '/consumer-finance'
      preLoaderRoute: typeof ConsumerFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cac-calculator': {
      id: '/cac-calculator'
      path: '/cac-calculator'
      fullPath: '/cac-calculator'
      preLoaderRoute: typeof CacCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appliance-repair': {
      id: '/appliance-repair'
      path: '/appliance-repair'
      fullPath: '/appliance-repair'
      preLoaderRoute: typeof ApplianceRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/society-mortgage': {
      id: '/case-studies/society-mortgage'
      path: '/case-studies/society-mortgage'
      fullPath: '/case-studies/society-mortgage'
      preLoaderRoute: typeof CaseStudiesSocietyMortgageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/mountain-gaming': {
      id: '/case-studies/mountain-gaming'
      path: '/case-studies/mountain-gaming'
      fullPath: '/case-studies/mountain-gaming'
      preLoaderRoute: typeof CaseStudiesMountainGamingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplianceRepairRoute: ApplianceRepairRoute,
  BookRoute: BookRoute,
  CacCalculatorRoute: CacCalculatorRoute,
  ConsumerFinanceRoute: ConsumerFinanceRoute,
  EcommerceRoute: EcommerceRoute,
  FreeAuditRoute: FreeAuditRoute,
  GrowthCalculatorRoute: GrowthCalculatorRoute,
  GrowthCeilingRoute: GrowthCeilingRoute,
  GtaSmallBusinessRoute: GtaSmallBusinessRoute,
  HvacRoute: HvacRoute,
  LocalServicesRoute: LocalServicesRoute,
  MetaAdsRoute: MetaAdsRoute,
  NotALeadsProblemRoute: NotALeadsProblemRoute,
  PrivacyRoute: PrivacyRoute,
  SaasRoute: SaasRoute,
  TorontoRoute: TorontoRoute,
  CaseStudiesMountainGamingRoute: CaseStudiesMountainGamingRoute,
  CaseStudiesSocietyMortgageRoute: CaseStudiesSocietyMortgageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
